[package]
name = "datadriven"
version = "0.1.0"
authors = ["Justin Jaffray <justin.jaffray@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Rewritable table-driven testing"
repository = "https://github.com/justinj/datadriven"
homepage = "https://github.com/justinj/datadriven"
readme = "README.md"

[dependencies]
anyhow = "1.0"
